/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : QL
 #	author : miyako
 #	2017/10/07
 #
 # --------------------------------------------------------------------------------*/

#import <QuickLook/QuickLook.h>
#import <Quartz/Quartz.h>

#import "libjson.h"

/*
 because we are using private APIs, it is imperative that...
 1. we compile as obj-c (not obj-c++)
 2. we don't use .pch or carbon framework
 */

typedef struct __QLPreview *QLPreviewRef;
QL_PRIVATE_EXPORT CFTypeID QLPreviewGetTypeID();

//create
QL_PRIVATE_EXPORT QLPreviewRef QLPreviewCreate(CFAllocatorRef, CFURLRef, CFDictionaryRef);
QL_PRIVATE_EXPORT void QLPreviewCancel(QLPreviewRef);
QL_PRIVATE_EXPORT void QLPreviewClose(QLPreviewRef);

//copy
QL_PRIVATE_EXPORT CFDataRef QLPreviewCopyData(QLPreviewRef);
QL_PRIVATE_EXPORT CFURLRef QLPreviewCopyDocumentURL(QLPreviewRef);
QL_PRIVATE_EXPORT CFDictionaryRef QLPreviewCopyProperties(QLPreviewRef);
QL_PRIVATE_EXPORT CFDictionaryRef QLPreviewCopyOptions(QLPreviewRef);
QL_PRIVATE_EXPORT CFStringRef QLPreviewCopyPreviewContentType(QLPreviewRef);

//copy (usage unknown)
QL_PRIVATE_EXPORT CGImageRef QLPreviewCopyBitmapImage(QLPreviewRef);
QL_PRIVATE_EXPORT CFURLRef QLPreviewCopyURLRepresentation(QLPreviewRef);
QL_PRIVATE_EXPORT CFDataRef QLPreviewCopyNextData(QLPreviewRef);

//get
QL_PRIVATE_EXPORT CFStringRef QLPreviewGetDisplayBundleID(QLPreviewRef);
QL_PRIVATE_EXPORT CGSize QLPreviewGetPreviewSizeHint(QLPreviewRef);
QL_PRIVATE_EXPORT CFArrayRef QLPreviewGetInlinePreviewSupportedContentTypes(QLPreviewRef);
QL_PRIVATE_EXPORT CFStringRef QLPreviewTypeGetRawImageDisplayBundleID();
QL_PRIVATE_EXPORT CFStringRef QLPreviewTypeGetRawImageContentType();
/*
 _QLPreviewGetPreviewType (deprecated..?)
 _QLPreviewGetRepresentedObject
 */

//set
QL_PRIVATE_EXPORT void QLPreviewSetForceContentTypeUTI(QLPreviewRef, CFStringRef);
QL_PRIVATE_EXPORT void QLPreviewSetDisplayBundleID(QLPreviewRef, CFStringRef);

//misc
QL_PRIVATE_EXPORT CFStringRef QLPreviewTypeGetDisplayBundleIDForUTI(CFStringRef);
QL_PRIVATE_EXPORT CFIndex QLPreviewTypeGetDisplayBundleCount();

// --- QL
void QL_Create_thumbnail(sLONG_PTR *pResult, PackagePtr pParams);
void QL_Create_preview(sLONG_PTR *pResult, PackagePtr pParams);
